openapi: 3.0.0
info:
  title: Online-Store
  version: v1.0.0
  description: This API contains operations related to online shopping store.
x-wso2-basePath: /store/{version}
x-wso2-production-endpoints:
  urls:
   - http://products
paths:
  /products:
    get:
      responses:
        200:
          description: successful operation
  /products/{productId}:
    get:
      parameters:
       -
        name: productId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
